### ISSUE TITLE
Programming in Beagle Bone

### ISSUE THREAD

**Issue by Rohi23** [adafruit/adafruit-beaglebone-io-python#203]
Hello everyone,

We are developing a industrial gateway on pocket beagle bone.

For the standalone application we want to write the python code.  So that during boot up we will add C Project binaries  &  Python Project binaries.

Just want to know if we can use both C and Python for the development .

**Comment by pdp7** [comment]
@Rohi23 you might be interested in the C++ support that @cocasema added in PR #135 to allow the Adafruit_BBIO functionality to be utilized from C++ instead of Python:
https://github.com/adafruit/adafruit-beaglebone-io-python/pull/135#issuecomment-290798115

Please open a new issue if you a specific problem regarding Adafruit_BBIO.
